### ISSUE TITLE
Mandatory args in subcommand results in a Null check operator error (version 2.1.0)

### ISSUE THREAD

**Issue by smayas** [dart-lang/args#197]
Some pseudo code:
```
// build_command.dart
class BuildCommand extends Command {
  BuildCommand(String repositoryUrl) {
    this.argParser.addOption('branch', mandatory: true, help: 'The target branch to build and deploy from');
  }

  @override
  Future<void> run() async {
    // whatever
  } 
}
// main.dart
final runner       = CommandRunner('bin/main.dart', 'Example Tool');
runner.addCommand(new BuildCommand('...'));
runner.run(args)
```

Running the command with no arguments currently throws an error

`dart run bin/main.dart build`
```

Null check operator used on a null value
_#0      CommandRunner.parse (package:args/command_runner.dart:127:51)
#1      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:36)
#2      new Future.sync (dart:async/future.dart:218:31)
#3      CommandRunner.run (package:args/command_runner.dart:112:14)_

`

**Comment by jakemac53** [comment]
Thanks for the report! This should be fixed now, released in version `2.1.1`
